name = "nak-server-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[d1_databases]]
binding = "DB"
database_name = "nak_minecraft"
database_id = "901517dc-ca9e-4191-826b-c4f758e67c17"
